name: show Info
on:
  [push]
  
jobs:
  showEvent:
    name: Show event info
    runs-on: [ubuntu-18.04]
    steps:
      - name: github event
        env:
          GITHUB_EVENT_INFOS: ${{ toJson(github.event) }}
        run: |
          echo $GITHUB_EVENT_INFOS
          echo ${{ github.event.head_commit.message }}
